headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[[forms]]
name = "contact"

[forms.notifications]
email = "support@mydigisign.ai"
subject = "New Contact Form Submission - MyDigiSign.AI"

[functions]

[functions."*"]

[build]
publish = "/Users/newfacetv/Desktop/NewFaceTV/GiT/MYDIGISIGN/website"
publishOrigin = "config"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: https://pagead2.googlesyndication.com; connect-src 'self' https://www.google-analytics.com https://pagead2.googlesyndication.com; frame-src 'self' https://googleads.g.doubleclick.net https://tpc.googlesyndication.com;"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.webp"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff2"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.ico"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/blog"
to = "/blog/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]